### ISSUE TITLE
Unresolved library: AsyncLibrary.

### ISSUE THREAD

**Issue by dzvancuks** [rlehfeld/robotframework-async-keyword#9]
For some reason VSCode can't resolve this particular library

```
*** Settings ***
Library      AsyncLibrary

Unresolved library: AsyncLibrary.
Error generating libspec:
Initializing library 'AsyncLibrary' with no arguments failed: RobotNotRunningError: Cannot access execution context
robotframework

Test Async
    ${tmp handle}=    Async Run    Tmp Test

Undefined keyword: Async Run.
robotframework
```
Might it be caused by previous lib usage - AsyncLibrary from `robotframework-async`? However I've cleared all PIP installations and re-installed requirements
```
robotframework>=7.0
robotframework-rammbock-py3
robotframework-redislibrary
protobuf
grpcio
grpcio-tools
robotframework-requests
robotframework-async-keyword
```

**Comment by Syman123** [comment]
Hi, I have the same problem in VSCode. 
- Installed AsyncLibrary
- Deinstalled AsyncLibrary. Installed Fork of AsyncLibrary

Result: 

Unresolved library: AsyncLibrary.
Error generating libspec:
Initializing library 'AsyncLibrary' with no arguments failed: RobotNotRunningError: Cannot access execution contextrobotframework

Any ideas yet?

**Comment by rasjani** [comment]
This is triggered  by the Language Server Protocol but could be remedied within this library.

LSP will try to create an instance of the library in order to get the list keywords from it by calling the constructor of the library. However, at this point, Robot Framework is not running.

Now, on AsyncLibrary, when its own constructor is called, self._postpone is initialized  but Postpone class calls robot's BuiltIn() -- which will throw RobotNotRunningError when the constructor is called from LSP.

**Comment by rlehfeld** [comment]
Hi,

thanks for raising this report and poposing a solution. This library is heavily doing monkey patching and should do this at the ealiest point to catch robot framework in a mostly consitent state. Therefore lazy evaluation is not the right approach. But I understand the problem and have already a fix in the pipe which is not so much different and instead relies on the information available in BuiltIn() and using as fallback the listener interface from robot framework
